/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum AccountTransactionType {
    Charge = <any> 'charge',
    Fee = <any> 'fee',
    Payment = <any> 'payment',
    Refund = <any> 'refund',
    Waive = <any> 'waive',
    Credit = <any> 'credit'
}
