/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CreditDistribution } from './creditDistribution';

export class ApplyCredit {
    /**
    * Credit distributions
    */
    'creditDistributions': Array<CreditDistribution>;
    /**
    * Action to apply credit.
    */
    'action': ApplyCredit.ActionEnum = ApplyCredit.ActionEnum.ApplyCredit;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "creditDistributions",
            "baseName": "creditDistributions",
            "type": "Array<CreditDistribution>"
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "ApplyCredit.ActionEnum"
        }    ];

    static getAttributeTypeMap() {
        return ApplyCredit.attributeTypeMap;
    }
}

export namespace ApplyCredit {
    export enum ActionEnum {
        WaiveFee = <any> 'WAIVE_FEE',
        AddFee = <any> 'ADD_FEE',
        ApplyCredit = <any> 'APPLY_CREDIT'
    }
}
