/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum EBillingCycleTypeEnum {
    FirstOfMonth = <any> 'FIRST_OF_MONTH',
    EndOfMonth = <any> 'END_OF_MONTH',
    Anniversary30 = <any> 'ANNIVERSARY_30',
    Anniversary31 = <any> 'ANNIVERSARY_31',
    FourWeekCycle = <any> 'FOUR_WEEK_CYCLE'
}
