/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// Comment to trigger build

import { RequestFile } from './models';

export class FeeDetails {
    /**
    * ID of the fee.
    */
    'feeId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "feeId",
            "baseName": "feeId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return FeeDetails.attributeTypeMap;
    }
}

