/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AddFee } from './addFee';
import { ApplyCredit } from './applyCredit';
import { CreditDistribution } from './creditDistribution';
import { FeeDetails } from './feeDetails';
import { WaiveFee } from './waiveFee';

/**
* Action payload
*/
export class InvoiceLineItemActionRequestPayload {
    /**
    * ID of the invoice line item to waive
    */
    'invoiceLineItemId': string;
    /**
    * Action to apply credit.
    */
    'action': InvoiceLineItemActionRequestPayload.ActionEnum = InvoiceLineItemActionRequestPayload.ActionEnum.ApplyCredit;
    'feeDetails': FeeDetails;
    /**
    * Credit distributions
    */
    'creditDistributions': Array<CreditDistribution>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "invoiceLineItemId",
            "baseName": "invoiceLineItemId",
            "type": "string"
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "InvoiceLineItemActionRequestPayload.ActionEnum"
        },
        {
            "name": "feeDetails",
            "baseName": "feeDetails",
            "type": "FeeDetails"
        },
        {
            "name": "creditDistributions",
            "baseName": "creditDistributions",
            "type": "Array<CreditDistribution>"
        }    ];

    static getAttributeTypeMap() {
        return InvoiceLineItemActionRequestPayload.attributeTypeMap;
    }
}

export namespace InvoiceLineItemActionRequestPayload {
    export enum ActionEnum {
        WaiveFee = <any> 'WAIVE_FEE',
        AddFee = <any> 'ADD_FEE',
        ApplyCredit = <any> 'APPLY_CREDIT'
    }
}
