/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InvoiceLineItemResponse {
    /**
    * Line Item ID.
    */
    'invoiceLineItemId': string;
    /**
    * Unit id.
    */
    'unitId'?: string;
    /**
    * Product id.
    */
    'productId'?: string;
    /**
    * Refers to either unitName or productName.
    */
    'name': string;
    /**
    * Description
    */
    'description': string;
    /**
    * Quantity
    */
    'quantity'?: number;
    /**
    * The recurring monthly rate in the smallest currency unit (e.g. cents for USD) or the one-time price (if product).
    */
    'price': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "invoiceLineItemId",
            "baseName": "invoiceLineItemId",
            "type": "string"
        },
        {
            "name": "unitId",
            "baseName": "unitId",
            "type": "string"
        },
        {
            "name": "productId",
            "baseName": "productId",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return InvoiceLineItemResponse.attributeTypeMap;
    }
}

