/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum InvoiceStatus {
    Due = <any> 'due',
    Paid = <any> 'paid',
    Pending = <any> 'pending',
    Unpaid = <any> 'unpaid',
    Draft = <any> 'draft',
    Overdue = <any> 'overdue'
}
