/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InvoiceLineItemAdjustmentResponse {
    /**
    * Adjustment ID
    */
    'invoiceLineItemAdjustmentId': string;
    /**
    * Invoice Line Item ID
    */
    'invoiceLineItemId': string;
    /**
    * Adjustment amount
    */
    'amount': number;
    /**
    * Description.
    */
    'description': string | null;
    /**
    * Created by
    */
    'createdBy': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "invoiceLineItemAdjustmentId",
            "baseName": "invoiceLineItemAdjustmentId",
            "type": "string"
        },
        {
            "name": "invoiceLineItemId",
            "baseName": "invoiceLineItemId",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InvoiceLineItemAdjustmentResponse.attributeTypeMap;
    }
}

