/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Invoice ID and status
*/
export class InvoiceV2LineItemResponseInvoice {
    'invoiceId'?: string;
    'invoiceStatus'?: InvoiceV2LineItemResponseInvoice.InvoiceStatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "invoiceId",
            "baseName": "invoiceId",
            "type": "string"
        },
        {
            "name": "invoiceStatus",
            "baseName": "invoiceStatus",
            "type": "InvoiceV2LineItemResponseInvoice.InvoiceStatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return InvoiceV2LineItemResponseInvoice.attributeTypeMap;
    }
}

export namespace InvoiceV2LineItemResponseInvoice {
    export enum InvoiceStatusEnum {
        Due = <any> 'due',
        Paid = <any> 'paid',
        Pending = <any> 'pending',
        Unpaid = <any> 'unpaid',
        Draft = <any> 'draft',
        Overdue = <any> 'overdue'
    }
}
