/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EBillingCycleTypeEnum } from './eBillingCycleTypeEnum';
import { EInvoicePeriodType } from './eInvoicePeriodType';

export class InvoiceRunResponse {
    /**
    * Invoice run ID
    */
    'invoiceRunId': string;
    /**
    * Org ID
    */
    'orgId': string;
    'invoicePeriodType': EInvoicePeriodType;
    'billingCycleType': EBillingCycleTypeEnum;
    /**
    * Invoice period start date
    */
    'invoicePeriodStartDate': Date;
    /**
    * Invoice period end date
    */
    'invoicePeriodEndDate': Date;
    /**
    * Created at
    */
    'createdAt': Date;
    /**
    * Created by
    */
    'createdBy': string;
    /**
    * Success.
    */
    'successful': boolean;
    /**
    * Error
    */
    'error': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "invoiceRunId",
            "baseName": "invoiceRunId",
            "type": "string"
        },
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string"
        },
        {
            "name": "invoicePeriodType",
            "baseName": "invoicePeriodType",
            "type": "EInvoicePeriodType"
        },
        {
            "name": "billingCycleType",
            "baseName": "billingCycleType",
            "type": "EBillingCycleTypeEnum"
        },
        {
            "name": "invoicePeriodStartDate",
            "baseName": "invoicePeriodStartDate",
            "type": "Date"
        },
        {
            "name": "invoicePeriodEndDate",
            "baseName": "invoicePeriodEndDate",
            "type": "Date"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string"
        },
        {
            "name": "successful",
            "baseName": "successful",
            "type": "boolean"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return InvoiceRunResponse.attributeTypeMap;
    }
}

export namespace InvoiceRunResponse {
}
