/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class LedgerResponseDto {
    /**
    * The Ledger ID
    */
    'ledgerId': string;
    /**
    * The Organization ID
    */
    'orgId': string;
    /**
    * The site ID
    */
    'siteId': string;
    /**
    * The unit ID
    */
    'unitId': string;
    /**
    * The rental ID
    */
    'rentalId': string;
    /**
    * Start date of the rental.
    */
    'periodStart': string;
    /**
    * End date of the rental.
    */
    'periodEnd': string | null;
    /**
    * Ledger balance.
    */
    'balance': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ledgerId",
            "baseName": "ledgerId",
            "type": "string"
        },
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string"
        },
        {
            "name": "siteId",
            "baseName": "siteId",
            "type": "string"
        },
        {
            "name": "unitId",
            "baseName": "unitId",
            "type": "string"
        },
        {
            "name": "rentalId",
            "baseName": "rentalId",
            "type": "string"
        },
        {
            "name": "periodStart",
            "baseName": "periodStart",
            "type": "string"
        },
        {
            "name": "periodEnd",
            "baseName": "periodEnd",
            "type": "string"
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return LedgerResponseDto.attributeTypeMap;
    }
}

