/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TransactionSummaryResponse } from './transactionSummaryResponse';

export class LedgerDetailsResponse {
    /**
    * The Ledger ID
    */
    'ledgerId': string;
    /**
    * The Organization ID
    */
    'orgId': string;
    /**
    * The site ID
    */
    'siteId': string;
    /**
    * The unit ID
    */
    'unitId': string;
    /**
    * The rental ID
    */
    'rentalId': string;
    /**
    * Start date of the rental.
    */
    'periodStart': string;
    /**
    * End date of the rental.
    */
    'periodEnd': string | null;
    /**
    * Ledger balance.
    */
    'balance': number;
    /**
    * Ledger Amount due
    */
    'totalDue': number;
    /**
    * Ledger Amount paid.
    */
    'totalPaid': number;
    /**
    * Account Name
    */
    'accountName': string;
    /**
    * Email
    */
    'email': string | null;
    /**
    * Mobile Number
    */
    'mobileNumber': string;
    /**
    * Transaction Summary.
    */
    'transactionsSummary': Array<TransactionSummaryResponse>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ledgerId",
            "baseName": "ledgerId",
            "type": "string"
        },
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string"
        },
        {
            "name": "siteId",
            "baseName": "siteId",
            "type": "string"
        },
        {
            "name": "unitId",
            "baseName": "unitId",
            "type": "string"
        },
        {
            "name": "rentalId",
            "baseName": "rentalId",
            "type": "string"
        },
        {
            "name": "periodStart",
            "baseName": "periodStart",
            "type": "string"
        },
        {
            "name": "periodEnd",
            "baseName": "periodEnd",
            "type": "string"
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "number"
        },
        {
            "name": "totalDue",
            "baseName": "totalDue",
            "type": "number"
        },
        {
            "name": "totalPaid",
            "baseName": "totalPaid",
            "type": "number"
        },
        {
            "name": "accountName",
            "baseName": "accountName",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "mobileNumber",
            "baseName": "mobileNumber",
            "type": "string"
        },
        {
            "name": "transactionsSummary",
            "baseName": "transactionsSummary",
            "type": "Array<TransactionSummaryResponse>"
        }    ];

    static getAttributeTypeMap() {
        return LedgerDetailsResponse.attributeTypeMap;
    }
}

