/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ReducedInvoiceV2LineItem {
    /**
    * Line Item ID.
    */
    'invoiceLineItemId': string;
    /**
    * Site ID
    */
    'siteId': string;
    /**
    * Org ID
    */
    'orgId': string;
    /**
    * Account ID
    */
    'accountId': string;
    /**
    * Description
    */
    'description': string | null;
    /**
    * Quantity
    */
    'quantity': number | null;
    /**
    * The recurring monthly rate in the smallest currency unit (e.g. cents for USD) or the one-time price (if product).
    */
    'unitPrice': number;
    /**
    * Product ID
    */
    'productId': string | null;
    /**
    * Rental ID
    */
    'rentalId': string | null;
    /**
    * Fee ID
    */
    'feeId': string | null;
    /**
    * Ledger ID
    */
    'ledgerId': string | null;
    /**
    * Tag.
    */
    'tag': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "invoiceLineItemId",
            "baseName": "invoiceLineItemId",
            "type": "string"
        },
        {
            "name": "siteId",
            "baseName": "siteId",
            "type": "string"
        },
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string"
        },
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        },
        {
            "name": "unitPrice",
            "baseName": "unitPrice",
            "type": "number"
        },
        {
            "name": "productId",
            "baseName": "productId",
            "type": "string"
        },
        {
            "name": "rentalId",
            "baseName": "rentalId",
            "type": "string"
        },
        {
            "name": "feeId",
            "baseName": "feeId",
            "type": "string"
        },
        {
            "name": "ledgerId",
            "baseName": "ledgerId",
            "type": "string"
        },
        {
            "name": "tag",
            "baseName": "tag",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReducedInvoiceV2LineItem.attributeTypeMap;
    }
}

