/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InvoiceStatus } from './invoiceStatus';

export class TransactionSummaryResponse {
    /**
    * Invoice ID.
    */
    'invoiceId': string;
    /**
    * Sequential Invoice Number.
    */
    'invoiceNumber': number;
    'invoiceStatus': InvoiceStatus;
    /**
    * Invoice period end date.
    */
    'invoicePeriodEndDate': Date | null;
    /**
    * Invoice id
    */
    'invoiceLineItemId': string;
    /**
    * inferred status for invoice line item
    */
    'status': TransactionSummaryResponse.StatusEnum;
    /**
    * Amount due
    */
    'due': number;
    /**
    * Amount paid.
    */
    'paid': number;
    /**
    * Item description/transaction notes.
    */
    'description': string;
    /**
    * Transaction date.
    */
    'transactionDate': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "invoiceId",
            "baseName": "invoiceId",
            "type": "string"
        },
        {
            "name": "invoiceNumber",
            "baseName": "invoiceNumber",
            "type": "number"
        },
        {
            "name": "invoiceStatus",
            "baseName": "invoiceStatus",
            "type": "InvoiceStatus"
        },
        {
            "name": "invoicePeriodEndDate",
            "baseName": "invoicePeriodEndDate",
            "type": "Date"
        },
        {
            "name": "invoiceLineItemId",
            "baseName": "invoiceLineItemId",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "TransactionSummaryResponse.StatusEnum"
        },
        {
            "name": "due",
            "baseName": "due",
            "type": "number"
        },
        {
            "name": "paid",
            "baseName": "paid",
            "type": "number"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "transactionDate",
            "baseName": "transactionDate",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return TransactionSummaryResponse.attributeTypeMap;
    }
}

export namespace TransactionSummaryResponse {
    export enum StatusEnum {
        Paid = <any> 'paid',
        Unpaid = <any> 'unpaid'
    }
}
