/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UnpaidWithBalance {
    /**
    * Invoice ID.
    */
    'lineItemId': string;
    /**
    * Outstanding balance for a line item (e.g. cents for USD).
    */
    'outstandingBalance': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "lineItemId",
            "baseName": "lineItemId",
            "type": "string"
        },
        {
            "name": "outstandingBalance",
            "baseName": "outstandingBalance",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return UnpaidWithBalance.attributeTypeMap;
    }
}

