/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InvoiceStatus } from './invoiceStatus';

export class UpdateInvoiceStatusRequestDto {
    'invoiceStatus': InvoiceStatus;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "invoiceStatus",
            "baseName": "invoiceStatus",
            "type": "InvoiceStatus"
        }    ];

    static getAttributeTypeMap() {
        return UpdateInvoiceStatusRequestDto.attributeTypeMap;
    }
}

export namespace UpdateInvoiceStatusRequestDto {
}
