/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WaiveFee {
    /**
    * ID of the invoice line item to waive
    */
    'invoiceLineItemId': string;
    /**
    * Action to waive fee
    */
    'action': WaiveFee.ActionEnum = WaiveFee.ActionEnum.WaiveFee;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "invoiceLineItemId",
            "baseName": "invoiceLineItemId",
            "type": "string"
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "WaiveFee.ActionEnum"
        }    ];

    static getAttributeTypeMap() {
        return WaiveFee.attributeTypeMap;
    }
}

export namespace WaiveFee {
    export enum ActionEnum {
        WaiveFee = <any> 'WAIVE_FEE',
        AddFee = <any> 'ADD_FEE',
        ApplyCredit = <any> 'APPLY_CREDIT'
    }
}
